sonar.projectKey=Qwickly
sonar.projectName=Qwickly
sonar.sources=qwickly,demo
sonar.tests=tests
sonar.exclusions=**/migrations/**,**/static/vendor/**,**/node_modules/**
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12
# Uncomment if you generate coverage.xml (pytest --cov=qwickly --cov-report=xml)
# sonar.python.coverage.reportPaths=coverage.xml
